CREATE DATABASE BW4_ECOMMERCE;

USE BW4_ECOMMERCE;

CREATE TABLE PRODUCTS(
Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
Name NVARCHAR(50) NOT NULL,
Price MONEY NOT NULL,
Description NVARCHAR(200) NOT NULL,
Img NVARCHAR(MAX) NOT NULL
)

CREATE TABLE CART(
Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
Name NVARCHAR(50) NOT NULL,
Price MONEY NOT NULL,
Img NVARCHAR(MAX) NOT NULL,
IdProduct UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT FK_IdProduct FOREIGN KEY (IdProduct) REFERENCES PRODUCTS(Id)
)
